README.md
Update README to match the README structure for susi_android
=> fixes #24: update README

Susi/Controllers/LoginViewController.swift, Susi/SignUpViewController.swift
Fixed LoginViewController and SignUpViewController UI, added keyboard dismiss functionality
Issue Mentioned - #28
=> UI enhancement of LoginViewController, SignUpViewController

.travis.yml, Susi.xcworkspace/xcshareddata/xcschemes/Susi.xcscheme, build.sh
Fixes #35:
Enables caching of dependencies as well as reduce build time considerably.
=> Fixes #35 Enable caching of dependencies

Susi/Constants.swift, Susi/MainViewController.swift
Fixes #16 : Send ISO 639-1 of configured language to the server for queries
=> Send ISO 639-1 of configured language to the server for queries

README.md
Adds instructions to install cocoapods
=> Setup instructions for cocoapods

Susi/Base.lproj/LaunchScreen.storyboard
=> Fixes #42: adds the Launch Screen UI 

Susi/Info.plist, Susi/MainViewController.swift
Adds user coordinates while calling the API
=> Add user location to the API

.travis.yml, upload-ipa.sh
Fixes Issue #22 
- Created script for uploading .app to the IPA branch on GitHub
=> Fixes #22: Create an ipa branch and add regular builds for iOS

Podfile, Podfile.lock, Susi.xcodeproj/project.pbxproj, Susi/AppDelegate.swift, Susi/AppNavigationController.swift, Susi/BaseCell.swift, Susi/ChatMessageCell.swift, Susi/Client.swift, Susi/Color.swift, Susi/Constants.swift, Susi/Controllers/LoginViewController.swift, Susi/Convenience.swift, Susi/Extensions.swift, Susi/MainViewController.swift, Susi/Message.swift, Susi/SettingsCell.swift, Susi/SettingsHeaderView.swift, Susi/SettingsViewController.swift, Susi/SignUpViewController.swift, Susi/User.swift, Susi/WebsearchResult.swift, Susi/YTPlayer.html, Susi/YouTubePlayer.swift, SusiUITests/SusiUITests.swift, build.sh
Fixes https://github.com/fossasia/susi_iOS/issues/61 : Use Youtube API to play videos
=> Add ability to play youtube videos

README.md
Fixes Issue https://github.com/fossasia/susi_iOS/issues/69: Add appetize.io badge
=> Add appetize.io badge

.github/ISSUE_TEMPLATE, .github/PULL_REQUEST_TEMPLATE
=> Fixes#66: Added template for issues and pull requests

Susi.xcodeproj/project.pbxproj, Susi/ControllerConstants.swift, Susi/Info.plist, Susi/MainViewController.swift
Fixes #20 
Added ability to select wallpaper and clear a previous wallpaper, with wallpaper saved in app default as per android susi app.
Implementation Screenshots are attached below
=> Fixes #20 Added Logic for wallpaper selection from gallery, and a dialog to clear wallpaper 

README.md, docs/commitStyle.md
Fixes issue #73 
Changes: Changed commit style guidelines and added screenshots of app in docs.
=> docs: Changing commit style guidelines and adding screenshots

Podfile.lock, Susi/BaseCell.swift, Susi/Controllers/LoginViewController.swift, Susi/Extensions.swift, Susi/MainViewController.swift, Susi/SignUpViewController.swift, build.sh
Fixes issue https://github.com/fossasia/susi_iOS/issues/63
Changes: Removed left codacy styling issues
=> style: codacy style issues and warnings

Podfile, Podfile.lock, Susi/ChatMessageCell.swift, Susi/Client.swift, Susi/Convenience.swift, Susi/Extensions.swift, Susi/MainViewController.swift, Susi/Message.swift
Fixes issue https://github.com/fossasia/susi_iOS/issues/48: Adds GIF Support
=> Fix #48: Add GIF support

Susi/MainViewController.swift
Fixes issue #15: show the last message partly hidden under the input field
Changes: 
- Updated frames of collectionView
=> fix #15: completely show last message which was hidden

Susi.xcodeproj/project.pbxproj, Susi/Color.swift, Susi/Constants.swift, Susi/ControllerConstants.swift, Susi/Controllers/LoginViewController.swift, Susi/Convenience.swift, Susi/Extensions.swift, Susi/ForgotPasswordViewController.swift, Susi/SignUpViewController.swift
Fixes issue #46: Forgot Password is not working
Changes:
- Added forgot password view
- Added API call to the forgot password API
Not sure why the GIFs show every transition so slow :(
=> fix: add forgot password functionality

Susi/Model/WebsearchResult.swift
Fixes issue #84 
Changes: 
- Improved Logic (Parse web search response only if array length > 0)
=> fix #84: App is crashing sometimes when reply is websearch type

Susi/Controllers/MainViewController/MainVCMethods.swift
Fixes issue #92 
Changes: 
- Removed hard coded check for playing a video
=> Fix: remove hardcoded video play

Susi/Controllers/LoginController/LoginVCMethods.swift
Fixes issue #98 
Changes: 
- Moved setting server path before login API called
=> Fix: crash on login

Podfile, Podfile.lock, Susi/Controllers/MainViewController/MainViewController.swift, Susi/Custom Views/Message Cells/ChatMessageCell.swift, Susi/Custom Views/Message Cells/IncomingChatCell.swift, Susi/Custom Views/Message Cells/OutgoingChatCell.swift
Fixes issue #101 
Changes: 
- Added timestamp label
- Formatted date to show in "HH:mm a" format: "17:48 PM"
=> fix #101: add time stamp for messages

Susi/Controllers/LoginController/LoginVCMethods.swift
Fixes issue #103 
Changes: 
- Updated scroll view content size
- Enabled the scroll property
=> Fix: scroll view scrolls now on lower device sizes

Susi/Controllers/MainViewController/MainVCDelegates.swift
Fixes issue #109 
Changes: 
- Clear DB on logout
=> feat: remove messages on logout

Susi/Controllers/MainViewController/MainVCDelegates.swift, Susi/Controllers/MainViewController/MainVCMethods.swift, Susi/Controllers/MainViewController/MainViewController.swift, Susi/Controllers/SettingsViewController.swift
Fixes issue #111
Changes: 
- Use settings to handle Hit return to Send
- Fixed wrong reference of user default keys
=> Fix #111: use settings options to perform actions

Susi/Controllers/LoginController/LoginVCMethods.swift, Susi/Model/Client/Constants.swift, Susi/Model/User.swift
Fixes issue #112 
Changes: 
- Check expiry time before current time auto login, if less -> logout else auto login
=> Fix #112: logout user after token expiry

Susi/Custom Views/Message Cells/IncomingChatCell.swift, Susi/Custom Views/Message Cells/OutgoingChatCell.swift
Fixes issue #115 
Changes: 
- Added min. message width
=> Fix: added a minimum message width

Susi/Controllers/LoginController/LoginVCMethods.swift, Susi/Controllers/LoginController/LoginViewController.swift, Susi/Custom Views/Message Cells/WebsearchCell.swift, Susi/Helpers/ControllerConstants.swift
Fixes issue #107 
Changes: 
- Added skip button
- Chat messages start fresh each time skip pressed (no history)
=> feat: anonymous mode implementation

Podfile, Podfile.lock, Susi/Controllers/ForgotPasswordController/ForgotPasswordVCMethods.swift, Susi/Controllers/LoginController/LoginVCMethods.swift, Susi/Controllers/MainViewController/MainVCDelegates.swift, Susi/Controllers/MainViewController/MainVCMethods.swift, Susi/Controllers/MainViewController/MainViewController.swift, Susi/Controllers/SignUpController/SignUpVCMethods.swift, Susi/Custom Views/Message Cells/IncomingChatCell.swift, Susi/Custom Views/Message Cells/WebsearchCell.swift, Susi/Custom Views/Message Cells/WebsearchCollectionView.swift, Susi/Model/Client/Convenience.swift, Susi/SnowboyWrapper.mm
Fixes issue #102 : memory leaks
Changes: 
- free snowboy data buffer
=> Fix: memory leaks

Susi/Controllers/MainViewController/MainVCDelegates.swift, Susi/Controllers/MainViewController/MainViewController.swift, Susi/Controllers/SettingsViewController.swift, Susi/Helpers/ControllerConstants.swift, Susi/Supporting Files/AppDelegate.swift
Fixes issue #125 
Changes: 
- added option to enable/disable hotword recognition in settings
- after detection through snowboy, STT starts
=> Fix: STT starts when hot word detected

Susi/Model/Client/Constants.swift
Fixes issue #127 
Changes:
- updated API URL to `api.susi.ai`
=> chore: api url update

Susi/Controllers/MainViewController/MainVCDelegates.swift, Susi/Controllers/MainViewController/MainVCMethods.swift, Susi/Controllers/MainViewController/MainViewController.swift
Fixes issue #146: STT not taking input always
Changes: 
- fixed send button disabling
- send query after no input
=> Feat: fix STT crash sometimes

Susi/Controllers/LoginController/LoginVCMethods.swift, Susi/Controllers/MainViewController/MainVCDelegates.swift, Susi/Controllers/SettingsViewController.swift, Susi/Helpers/ControllerConstants.swift, Susi/Helpers/Extensions.swift, Susi/Model/Client/Constants.swift, Susi/Model/Client/Convenience.swift
Fixes issue #149, #157 
Changes: 
- load user settings on login
- save settings on the server
- fixed audio buffer crash when hot word recognition started on load
=> Fix: save user settings on server, audio buffer empty crash

circle.yml
Fixes issue #164 
Changes: 
- updated reference of the owner in circle.yml
=> fix: owner reference

Susi.xcodeproj/project.pbxproj, circle.yml, upload-ipa.sh
Fixes issue #23: automatic builds upload ipa file to ipa branch
Changes: 
- updated circle script
- manually created the ipa file
=> fix: upload script to have .ipa file

Susi/Controllers/SettingsController/SettingsVCMethods.swift
Fixes issue #187 
Changes:
- checked if auth token exists
- used main thread to show toast instead of global
=> fix: update settings for authenticated users only

Podfile, Podfile.lock, Susi/Controllers/ForgotPasswordController/ForgotPasswordVCMethods.swift, Susi/Controllers/ForgotPasswordController/ForgotPasswordViewController.swift, Susi/Controllers/LoginController/LoginVCMethods.swift, Susi/Controllers/LoginController/LoginViewController.swift, Susi/Controllers/SignUpController/SignUpVCMethods.swift, Susi/Controllers/SignUpController/SignUpViewController.swift, Susi/Storyboards/Main.storyboard, SusiUITests/AuthenticationUITests.swift, SusiUITests/ChatUITests.swift
Fixes issue #189 
Changes: 
- removed standard server buttons from login, signup and forgot password
- fixed validator
=> Feat: remove standard server button

Susi/Controllers/SettingsController/SettingsVCMethods.swift
Fixes issue #197
Changes: 
- extract user defaults setting keys outside checking if user authenticated
N/A
=> Fix: save settings for anonymous users

Susi/Helpers/ControllerConstants.swift
Fixes issue #199 
Changes:
- update keys for settings
n/a
=> Chore: setting keys

Podfile.lock, Susi/Storyboards/Base.lproj/LaunchScreen.storyboard
=>  Fixes: #206 - splash screen added

docs/Internationalization.md
Add documentation for adding languages #203
=> Documentation - Internationalization

Susi/Controllers/ChatViewController/AudioRecorderDelegate.swift, Susi/Controllers/SettingsController/SettingsVCMethods.swift, Susi/Controllers/SettingsController/SettingsViewController.swift
Fixes #214 
Changes:
- functionality to share app added
=> feat: sharing option added

Susi/Controllers/ForgotPasswordController/ForgotPasswordVCMethods.swift, Susi/Controllers/LoginController/LoginVCMethods.swift, Susi/Controllers/SettingsController/SettingsViewController.swift, Susi/Controllers/SignUpController/SignUpVCMethods.swift, Susi/Controllers/SignUpController/SignUpViewController.swift, Susi/Controllers/SkillListingViewController/SkillListingVCMethods.swift, Susi/Storyboards/Main.storyboard
Fixes #222
Changes: 
- remove reset password showing up
- removed redundant code
N/A
=> Fix: reset password showing up, minor refactors

Susi/Controllers/ChatViewController/ChatVCMethods.swift
Since the button used to be hidden behind the iphoneX's status bar so i now programmatically calculate the height of the of the status bar and place the button accordingly.
Changes: [i changed the static height at which the skill listing button is placed and made it dynamic]
=> updated the way the chat listing button is placed

.github/ISSUE_TEMPLATE
Fixes #266 
Changes: Commented out suggestions statements.
=> Comment out suggestions in Issue Template

Podfile.lock, Susi.xcodeproj/project.pbxproj
Fixes #283 
Changes: Pods are updated to Latest Version 1.5.2.
=> Updating pods to Latest Version

Susi.xcodeproj/project.pbxproj, Susi/Controllers/ChatViewController/ChatVCMethods.swift, Susi/Controllers/ChatViewController/ChatViewController.swift, Susi/Controllers/SettingsController/SettingsViewController.swift, Susi/Helpers/ControllerConstants.swift, Susi/Storyboards/Main.storyboard, SusiUITests/SettingsUITests.swift
**Fixes** #278 
**Changes:** 
- Added a button on the chat screen to go directly to settings screen from chat screen
- Added **UI tests** for settings button
**Screenshots for the change:** 
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/20956124/40268326-fa3b3210-5b88-11e8-9ec9-4335452d2bba.gif"></td>
<td><img src="https://user-images.githubusercontent.com/20956124/40268299-80be6a6a-5b88-11e8-8802-74ca96e0dc74.png"></td>
<tr>
</table>
=> feat: added setting button on chat screen

Susi.xcodeproj/project.pbxproj, Susi/Controllers/ChatViewController/ChatVCMethods.swift, Susi/Controllers/ChatViewController/CollectionViewDelegate.swift, Susi/Controllers/ChatViewController/SpeechRecognizerDelegate.swift, Susi/Custom Views/Message Cells/StopCell.swift, Susi/Helpers/ControllerConstants.swift, Susi/Model/Message.swift
Fixes #292 
Changes:
Added support for **"stop"** action in SUSI response
**Demo Video Link:** [https://www.youtube.com/watch?v=krjMo14bgwI](https://www.youtube.com/watch?v=krjMo14bgwI)
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/20956124/40795500-e6af8fa2-651f-11e8-8744-c40229677bb5.png" width="400"</td>
</tr>
</table>
=> Added support for 'stop' action to chat

Susi.xcodeproj/project.pbxproj, Susi/Assets/Assets.xcassets/plus_icon.imageset/Contents.json, Susi/Assets/Assets.xcassets/plus_icon.imageset/plus_icon.pdf, Susi/Controllers/DevicesActivityController/DevicesActivityViewController.swift, Susi/Controllers/SettingsController/SettingsViewController.swift, Susi/Helpers/ControllerConstants.swift, Susi/Helpers/Extensions.swift, Susi/Storyboards/Main.storyboard, Susi/Storyboards/Main.storyboard.orig
Fixes #301 
Changes:
UI screen for device activity, if there is no device connected, there is a `Label` to show _You haven't added any devices yet_.
<table>
<tr>
<th>GIF</th>
<th>Screenshot</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Added the device UI screen for device activity

Susi/Controllers/SignUpController/SignUpVCMethods.swift, Susi/Controllers/SignUpController/SignUpViewController.swift, Susi/Helpers/ControllerConstants.swift
Fixes #338 
Changes: fixed problem connecting to the server during Signup
N/A
=> fix problem connecting to server during Signup

Susi.xcodeproj/project.pbxproj, Susi/Controllers/AllFeedbackController/AllFeedbackViewController.swift, Susi/Controllers/SkillDetailViewController/SkillDetailVCMethods.swift, Susi/Controllers/SkillDetailViewController/SkillDetailViewController.swift, Susi/Custom Views/Feedback Display Cell/AllFeedbackCell.swift, Susi/Custom Views/Feedback Display Cell/FeedbackDisplayCell.swift, Susi/Helpers/ControllerConstants.swift, Susi/Helpers/Extensions.swift, Susi/Model/Client/Constants.swift, Susi/Model/Client/Convenience.swift, Susi/Model/Feedback.swift, Susi/Storyboards/Main.storyboard
Fixes #359 , Parent issue #339 
Changes:
Displaying skill feedbacks in the Feedback section
- Display three feedbacks in Skill Detail Screen and click on see all review, display all feedbacks
- Handle case for less than or equal to three feedbacks
<table>
<tr>
<td>Feedbacks on Skill Detail</td>
<td>All Feedback</td>
</tr>
<tr>
<td>
</td>
<td>
</td></tr>
<tr>
<td>Feedback <= 3</td>
<td>No Feedback</td>
</tr>
<tr>
<td>
</td>
<td>
</td></tr>
</table>
=> Displaying skill feedbacks in the Feedback section

Susi/Controllers/SettingsController/SettingsVCMethods.swift, Susi/Storyboards/Main.storyboard
Fixes #357 
Changes:
Resolved Problem connecting to the server during changing user settings issue
N/A
=> Resolved Problem connecting to server during changing user settings

Susi/Controllers/LoginController/LoginVCMethods.swift, Susi/Helpers/ControllerConstants.swift, Susi/Helpers/Extensions.swift
Fixes #347 
Changes: Added URL validation for custom server URL
N/A
=> Added URL validation for custom server URL

Susi/Custom Views/Message Cells/ImageCell.swift, Susi/Custom Views/Message Cells/IncomingChatCell.swift, Susi/Custom Views/Message Cells/StopCell.swift, Susi/Helpers/ControllerConstants.swift
Fixes #380, #385 
Changes:
- Remove thumbs up and thumbs after successfully submitted feedback to prevent multiple feedbacks
- Fixed feedback not accepting issue
<table>
<tr>
<td>Before feedback (News)</td>
<td>After feedback (News)</td>
</tr>
<tr>
<td>
</td>
<td>
</td></tr>
</table>
=> thumbs up, thumbs down cannot be changed and fixed feedback not accepting

Susi/Model/Client/Constants.swift, Susi/Model/Client/Convenience.swift
Fixes #363 
Changes: Added method for feedback log API - `feedbackLog.json`
Corresponding Android PR: https://github.com/fossasia/susi_android/pull/1612
N/A
=> Added feedback log API

Susi.xcodeproj/project.pbxproj, Susi/Controllers/SkillDetailViewController/SkillDetailVCMethods.swift, Susi/Custom Views/Feedback Display Cell/AllFeedbackCell.swift, Susi/Custom Views/Feedback Display Cell/FeedbackDisplayCell.swift, Susi/Helpers/MD5Digest.swift, Susi/Storyboards/Main.storyboard
Fixes #406, Parent issue #399 
Changes:
- Added gravatar in the feedback section of **Skill Detail** Screen
- Added gravatar in **See All Feedback** screen
- Increases the height of `FeedbackDisplayCell`
Corresponding SUSI Android PR: https://github.com/fossasia/susi_android/pull/1645
<table>
<tr>
<td>Skill Detail Screen</td>
<td>See All Feedback</td>
</tr>
<tr>
<td>
</td>
<td>
</td></tr>
</table>
=> Integrated gravatar for users in feedback section

Susi/Controllers/ChatViewController/ChatVCMethods.swift, Susi/Custom Views/Message Cells/ImageCell.swift, Susi/Custom Views/Message Cells/IncomingChatCell.swift, Susi/Custom Views/Message Cells/StopCell.swift, Susi/Helpers/ControllerConstants.swift, Susi/Model/Client/Constants.swift
Fixes #404 
Changes: Added actions for `feedbackLog` API
N/A
=> Adding actions for feedbackLog API

Susi/Controllers/DevicesActivityController/DeviceActivityMethods.swift, Susi/Helpers/ControllerConstants.swift
Fixes #411 
Changes:
Changes the UI flow titles and messages strings similar to Google Home App
Corresponding SUSI Android PR: https://github.com/fossasia/susi_android/pull/1662
N/A
=> fix: add the strings similar to Google home

Susi/Controllers/DevicesActivityController/DeviceActivityMethods.swift
=> fix: App is crashing when proceeding after entering wi-fi password

Susi/Controllers/DevicesActivityController/DeviceActivityMethods.swift, Susi/Controllers/DevicesActivityController/DevicesActivityViewController.swift, Susi/Helpers/ControllerConstants.swift
Fixes #410 
Changes: Update device activity after the successful connection between SUSI iOS App and SUSI Smart Speaker and show the success message.
N/A
=> Finish connection between iOS App and Smart Speaker

Susi/Controllers/ChatViewController/ChatVCMethods.swift, Susi/Controllers/ChatViewController/ChatViewController.swift, Susi/Controllers/LoginController/LoginVCMethods.swift, Susi/Controllers/LoginController/LoginViewController.swift, Susi/Controllers/SkillListingViewController/SkillListingVCMethods.swift, Susi/Controllers/SkillListingViewController/SkillListingViewController.swift
Fixes #419 
Changes: Refactored code
N/A
=> refactor- refactored Reachability code

Susi/Custom Views/Feedback Display Cell/AllFeedbackCell.swift, Susi/Custom Views/Feedback Display Cell/FeedbackDisplayCell.swift, Susi/Model/Feedback.swift
Fixes #423 
Changes: Now, the feedback shows the name of the users if it exists otherwise it displays their email
Screenshot :
=> displays usernames in the feedback

Susi/Supporting Files/AppDelegate.swift
Fixes #427 
Changes: fixed the issue - the app is closing when login session is expired. Now, the login screen is presented when the session is expired.
N/A
=> [FIX] App is closing when login session is expired

Susi/Controllers/SkillDetailViewController/SkillDetailVCMethods.swift, Susi/Controllers/SkillDetailViewController/SkillDetailViewController.swift, Susi/Model/Client/Constants.swift, Susi/Model/Client/Convenience.swift
Fixes #429 
Changes:
- User can report skill in Skill Detail screen
- Only logged-in user can report skill
<table>
<tr>
<td>
</td>
<td>
</td></tr>
</table>
=> Adding feature to report a skill

Susi/Assets/Assets.xcassets/iOSBlue.colorset/Contents.json, Susi/Helpers/Color.swift, Susi/Storyboards/Main.storyboard
Fixes #437 
Changes: Changed the color primary of the app to #4285f4
N/A
=> fix: Use correct color primary to make it consistent with other clients

Susi/Controllers/SettingsController/SettingsVCMethods.swift
=> fix: Logout button is not working sometime

Susi/Controllers/SettingsController/SettingsViewController.swift
=> fix: Reset Password showing to Logged-out users

README.md
Fixes #446 
Changes: Homebrew command for installing cocoapods added.
=> Homebrew command for installing cocoapods added

Susi/Controllers/SkillDetailViewController/SkillDetailVCMethods.swift, Susi/Controllers/SkillListingViewController/SkillListingVCMethods.swift, Susi/Supporting Files/AppDelegate.swift, Susi/Supporting Files/Info.plist
Partially Fixes #436 
Changes: Implemented 3D-touch home action for SkillListing screen
=> Add 3D-touch home action for SkillListing screen

.circleci/config.yml, .swiftlint.yml, Podfile, Podfile.lock, Susi.xcodeproj/project.pbxproj, Susi/Controllers/ChatViewController/AudioRecorderDelegate.swift, Susi/Controllers/ChatViewController/ChatVCMethods.swift, Susi/Controllers/ChatViewController/CollectionViewDelegate.swift, Susi/Controllers/ChatViewController/SpeechRecognizerDelegate.swift, Susi/Controllers/DevicesActivityController/DeviceActivityMethods.swift, Susi/Controllers/OnboardingViewController/OnboardingViewController.swift, Susi/Controllers/PlayerViewController/PlayerViewController.swift, Susi/Controllers/SettingsController/SettingsVCMethods.swift, Susi/Controllers/SignUpController/SignUpVCMethods.swift, Susi/Controllers/SkillDetailViewController/SkillDetailVCCollectionView.swift, Susi/Controllers/SkillDetailViewController/SkillDetailVCMethods.swift, Susi/Controllers/SkillListingViewController/SkillListingViewController.swift, Susi/Controllers/SkillListingViewController/noConnectionViewController.swift, Susi/Controllers/TrainingViewController/TrainingAudioRecorderDelegate.swift, Susi/Custom Views/Message Cells/IncomingChatCell.swift, Susi/Custom Views/Message Cells/MapCell.swift, Susi/Custom Views/Message Cells/StopCell.swift, Susi/Custom Views/RatingView.swift, Susi/Helpers/Extensions.swift, Susi/Supporting Files/AppDelegate.swift, Susi/Youtube-Player/VideoPlayerView.swift
Fixes #443 
Changes:
Updated project swift syntaxes to the latest **`Swift 4.2`**
N/A
=> [UPDATE] Migrate code to swift 4.2 and Xcode 10.0

Susi/Controllers/SkillListingViewController/SkillListingVCMethods.swift, Susi/Controllers/SkillListingViewController/SkillListingViewController.swift
Changes: Added pull to refresh on Skill Listing Page  #462
=> Feat: Implemented Pull to Refresh feature on Skill Listing 

.circleci/config.yml, .swiftlint.yml, Susi/Controllers/ChatViewController/ChatVCMethods.swift, Susi/Controllers/DevicesActivityController/DeviceActivityMethods.swift, Susi/Controllers/LoginController/LoginVCMethods.swift, Susi/Controllers/PlayerViewController/PlayerViewController.swift, Susi/Controllers/RoomPickerController/RoomPickerController.swift, Susi/Controllers/SettingsController/SettingsVCMethods.swift, Susi/Controllers/SkillDetailViewController/SkillDetailVCMethods.swift, Susi/Custom Views/Message Cells/ImageCell.swift, Susi/Custom Views/Message Cells/IncomingChatCell.swift, Susi/Custom Views/Message Cells/OutgoingChatCell.swift, Susi/Custom Views/Message Cells/StopCell.swift, Susi/Custom Views/Message Cells/YouTubePlayerCell.swift, Susi/Custom Views/RatingView.swift, Susi/Helpers/Extensions.swift, Susi/Model/Client/Client.swift, Susi/Youtube-Player/VideoPlayerView.swift
=> Fix failing Circle-Ci Swiftlint

Susi/Storyboards/Main.storyboard
Fixes #467 
Changes: Fixed the bottom margin.
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td></tr>
</table>
=> fix: not-aligned bottom Skip/Login button on Onboarding screen

Susi/Controllers/SettingsController/SettingsViewController.swift
=> Reset Password Cell Fixed

Susi/Controllers/SettingsController/SettingsViewController.swift, Susi/Helpers/ControllerConstants.swift
=> Fix:Alert Controller in logout cell in SettingVC

Susi/Controllers/SkillDetailViewController/SkillDetailVCMethods.swift
Fixes #506 
Change content type from Non - Dynamic to Static , to make it similar to Android one
=> Fix:Change content-type from Non-Dynamic to Static

Podfile, Podfile.lock, Susi.xcodeproj/project.pbxproj, Susi/Controllers/SkillDetailViewController/SkillDetailVCMethods.swift, Susi/Controllers/SkillDetailViewController/SkillDetailViewController.swift, Susi/Helpers/ControllerConstants.swift, Susi/Model/Client/Constants.swift, Susi/Model/Skill.swift
Fixes #487 
Share Skill feature ob skill detail view controller
=> Feat: Share Skill Feature on Skill Detail View Controller

Susi/Custom Views/Message Cells/ChatMessageCell.swift, Susi/Custom Views/Message Cells/IncomingChatCell.swift
#512 fix
Problem: User is not able to hit like and dislike button when the cell appear first time. As Content view is not getting proper height . (Try initialising cell with clips to bounds to true).
Changes: I gave tableviewcell View and  ContentView correct height while layouting subviews
=> Like Dislike Button Fixed

Susi/Model/Message.swift
fix for #514 
Problem: The crash occur when there is Api success and still gets no data 
Solution : Added Count Check
=> Crash fix on ChatVC

Susi/Controllers/ResetPasswordController/ResetPasswordVCMethods.swift
Fixes #509 
Changes: make `isActive`  = true
=> Fix: Reset Password Functionality

Susi/Controllers/SkillDetailViewController/SkillDetailVCMethods.swift, Susi/Controllers/SkillDetailViewController/SkillDetailViewController.swift
Fixes #520 
Changes: show feedback by latest timestamp
=> Feat: Feedback by latest timestamp

Susi/Controllers/LoginController/LoginVCMethods.swift, Susi/Controllers/LoginController/LoginViewController.swift, Susi/Controllers/ResetPasswordController/ResetPasswordController.swift, Susi/Controllers/ResetPasswordController/ResetPasswordVCMethods.swift, Susi/Controllers/SignUpController/SignUpVCMethods.swift, Susi/Controllers/SignUpController/SignUpViewController.swift
Fixes #525 
changes :  Add delegate and use function textFieldshouldReturn  
Here is the video link 
[Switching Text Fields](https://youtu.be/ym0Mrtfurrw)
=> Fix:Switching between Text Fields

Susi/Controllers/LoginController/LoginVCMethods.swift, Susi/Controllers/LoginController/LoginViewController.swift
Fixes #491 
Changes: Change color of buttons from blue to white
=> Fix: Change buttons color

Susi/Controllers/LoginController/LoginVCMethods.swift
Fixes #528 
Changes: remove the unused code.
No SS needed.
=> Fix:Remove unused function

Susi/Controllers/SkillDetailViewController/SkillDetailVCMethods.swift, Susi/Controllers/SkillDetailViewController/SkillDetailViewController.swift, Susi/Model/Client/Constants.swift, Susi/Model/Skill.swift, Susi/Storyboards/Main.storyboard
Fixes #527 
Changes: Add skill details in Skill Details Vc
=> Feat:Add Skill Details in Skill DetailVC

Susi/Custom Views/LongPressToCopyTextView.swift, Susi/Custom Views/Message Cells/ChatMessageCell.swift, Susi/Custom Views/Message Cells/IncomingChatCell.swift
same as https://github.com/fossasia/susi_iOS/pull/518
=> Made Link in Chat View Clickable

Susi/Controllers/SettingsController/SettingsVCMethods.swift, Susi/Controllers/SettingsController/SettingsViewController.swift, Susi/Helpers/ControllerConstants.swift, Susi/Model/Client/Constants.swift, Susi/Storyboards/Main.storyboard
Fixes #541 
Changes: 
1: Add table view cell in setting Vc
2: Show user image and email in the cell
=> Feat: Add Account Section Cell in Setting View Controller.

Susi/Controllers/SkillDetailViewController/SkillDetailVCMethods.swift, Susi/Controllers/SkillDetailViewController/SkillDetailViewController.swift, Susi/Helpers/ControllerConstants.swift, Susi/Model/Client/Constants.swift, Susi/Model/Client/Convenience.swift
=> Feat: Bookmark and Unbookmark Skill.

Susi/Controllers/SettingsController/SettingsVCMethods.swift
Fixes #562 
Changes: Change the parameters inside the function
=> Fix: Fix Susi Settings Parameters

Susi/Controllers/SignUpController/SignUpVCMethods.swift, Susi/Model/Client/Convenience.swift
#566
Changes: Add guard let in Susi/Controllers/SignUpController/SignUpVCMethods.swift and   Susi/Model/Client/Convenience.swift
=> fix app crash on sign up

Susi/Storyboards/Main.storyboard
Fixes #508
Changes: Change Star colour in skill detailVC from iOS Blue to iOS Yellow
=> changing star color to yellow
