fossasia/susi_iOS

Podfile
Podfile.lock
Susi/Controllers/ForgotPasswordController/ForgotPasswordVCMethods.swift
Susi/Controllers/ForgotPasswordController/ForgotPasswordViewController.swift
Susi/Controllers/LoginController/LoginVCMethods.swift
Susi/Controllers/LoginController/LoginViewController.swift
Susi/Controllers/SignUpController/SignUpVCMethods.swift
Susi/Controllers/SignUpController/SignUpViewController.swift
Susi/Helpers/ControllerConstants.swift
Susi/Model/Client/Convenience.swift

Fixes issue #72: option to choose between custom and standard server
Changes: 
- Added radio buttons for toggling 
- Saved the URL in UserDefaults which can be used for making API calls

feat: option to switch between standard and custom server

---

Susi/Controllers/MainViewController/MainVCMethods.swift

Fixes issue #117 : pass access token with each request for authenticated users
Changes: 
- grab user object and pass the access token from the object in the request

Fix: pass access token with each request

---

upload-ipa.sh

Fixes issue #168 : Fixed the upload_ipa script to delete all the stale files and upload ipa properly. 
Changes: 
Modified upload_ipa.sh script to delete stale files, add new ipa to a fresh orphan branch and rename it to ipa just like I did in susi_android and open-event-android
Note:  It is working locally but I cannot confirm working until PR merges and Circle Build runs with a commit that is not in a Pull Request due to the check if ```[[ $CIRCLE_BRANCH != pull* ]]```
N/A

fixed the upload-ipa script

---

upload-ipa.sh

Fixes issue #168 which could not be completely solved in last pull request.
I checked the logs and there was pathspec error while attempting to delete .git folder. This PR uses a little different approach to remove stale files. It must work but again I cannot assure till it passes after merging.
@chashmeetsingh Please check the commands in this PR upto pushing to ipa branch on your system as well to confirm everything works.
N/A

fixed pathspec error in remove stale files command

---

Susi/Controllers/SignUpController/SignUpViewController.swift
Susi/Storyboards/Main.storyboard
SusiUITests/ChatUITests.swift

Changes: `SignUpViewController` is being presented modally so there should be a dismiss button pointing downwards instead of a back button. This PR changes the orientation of the back button by 90° thus not adding another image asset for it.
**Before Changes:** ![beforechange](https://user-images.githubusercontent.com/14364505/36372637-a0abe7dc-158b-11e8-8d06-fb407f629a58.png)
**After Changes:**![afterchange](https://user-images.githubusercontent.com/14364505/36372636-a06fe534-158b-11e8-851b-207fe58d89b2.png)

Downward Close Button on SignUpViewController

---

README.md

Fixes #37 : Added Swift Style Guide and iOS Good practices to **Code practices** section
Changes: As I mentioned in issue #37 I added Swift style guide and Good iOS Development Practices to Readme.md
Link for Style Guide: [Swift Style Guide](https://github.com/linkedin/swift-style-guide)
Link for good practices: [iOS Good Practices](https://github.com/futurice/ios-good-practices)

Added Style guide and Best Practices to readme.md

---

Susi/Controllers/SkillDetailViewController/SkillDetailVCMethods.swift
Susi/Controllers/SkillDetailViewController/SkillDetailViewController.swift
Susi/Controllers/SkillListingViewController/SkillListingVCMethods.swift
Susi/Custom Views/Skill Listing Cells/SkillCell.swift
Susi/Custom Views/Skill Listing Cells/SkillListingCollectionView.swift
Susi/Custom Views/Skill Listing Cells/SkillListingTableCell.swift
Susi/Storyboards/Main.storyboard

Fixes #272 
Changes: Improved the UI for Skill Listing and Skill Details screens
**Now:**
<table>
<tr>
<th>Skill Listing</th>
<th>Skill Details</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
**Before:**
<table>
<tr>
<th>Skill Listing</th>
<th>Skill Details</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

Improved UI for Skill Listing and Skill Details screens

---

Susi/Controllers/ChatViewController/ChatVCMethods.swift
Susi/Helpers/ControllerConstants.swift
Susi/Model/Client/Constants.swift

Fixes #334 
Changes:
Send device type in `chat.json` API calling Param
```
"device" : "iOS"
```
N/A

Sending device type in chat.json API

---

Susi/Controllers/ChatViewController/ChatVCMethods.swift
Susi/Model/Client/Constants.swift

Fixes #331 
Changes:
Sending country name and country code in `chat.json` API
N/A

Sending country name and country code in chat.json API

---

Susi.xcodeproj/project.pbxproj
Susi/Controllers/SkillDetailViewController/SkillDetailVCMethods.swift
Susi/Controllers/SkillDetailViewController/SkillDetailViewController.swift
Susi/Model/Client/Constants.swift
Susi/Model/Client/Convenience.swift
Susi/Model/Ratings.swift
Susi/Model/Skill.swift

Fixes #319 
Changes:
- Allow the user to rate the skill - `fiveStarRateSkill` API
- Update rating chart bar as soon as user rate the skills - response rating from `fiveStarRateSkill` API
- Update skill model for modified skill
- Display initial ratings on `RatingView` as filled star if the user already submitted that rating before - `getRatingByUser` API
- Handled all the possible cases for ratings carefully
See **video demonstration** here: https://drive.google.com/open?id=1LmDP8Do7pgbh72K5JHsq5E5ge8Zrvlme

Allowing the user to rate the skill and handled related cases

---

Susi/Supporting Files/AppDelegate.swift

Fixes #345 
Changes:
if the user is already logged-in before, directed the user to Chat screen without going to the login screen to avoid showing login screen to the logged-in user
GIF for the change:

fix showing login screen to the logged-in user issue

---

Susi/Controllers/ChatViewController/ChatVCMethods.swift
Susi/Controllers/ChatViewController/ChatViewController.swift
Susi/Controllers/ChatViewController/TextFieldDelegate.swift

Fixes #362 
Changes: Adding support for sending multiline text in chat
- Changes `UITextField` to `UITextView`
- Added `UITextViewDelegate` methods
- Handled `Enter to send`
GIF for the change: 
(Ignore bad quality of GIF - due to big size)

Adding support for sending multiline text in chat

---

Susi/Custom Views/Skill Listing Cells/SkillListingTableCell.swift

Fixes #337 
Changes: Skills are displayed in descending order of **average ratings**

Displaying skills in descending average ratings order

---

Susi/Controllers/ChatViewController/CollectionViewDelegate.swift
Susi/Model/Message.swift

Fixes #383 
Changes: Play video from youtube for `audio_play` action, same as the SUSI Android and Web client.
<table>
<tr>
<td>
</td>
<td>
</td></tr>
</table>

Adding support for audio_play action

---

Susi/Model/Client/Constants.swift
Susi/Model/Skill.swift

Fixes #389 
Changes: Make call to SUSI server instead of getting data from GitHub for skills images - `getImage` API
N/A

Make call to SUSI server instead of getting data from github

---

Susi/Custom Views/Feedback Display Cell/AllFeedbackCell.swift
Susi/Custom Views/Feedback Display Cell/FeedbackDisplayCell.swift

Fixes #408, Parent issue #399 
Changes: Anonymize the feedback and only show emails until the @ sign, e.g. "mariobehling@...".
<table>
<tr>
<td>Skill Detail Screen</td>
<td>See All Feedback</td>
</tr>
<tr>
<td>
</td>
<td>
</td></tr>
</table>

Anonymize the user email address in Feedback section

---

Susi/Controllers/SignUpController/SignUpVCMethods.swift
Susi/Helpers/ControllerConstants.swift
Susi/Model/Client/Constants.swift
Susi/Model/Client/Convenience.swift

Fixes #421 
Changes: Make use of `/aaa/checkRegistration.json` API to check if the user is already registered or not. If the user is already registered it show a toast.
N/A

Check if user already registered or not for signup

---

Susi/Storyboards/Main.storyboard

Fixes #325 
Changes: 
- Changes background to standard iOS color
- Added constraints
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td></tr>
</table>

Modify the UI of 'Reset Password' screen

---

Susi/Controllers/LoginController/LoginVCMethods.swift

Fixes #455 
Changes: Password length limit from login page is removed, as there is no requirement of showing minimum character limit in the login page.
GIF:

Password length limit removed from login page

---

Susi.xcodeproj/project.pbxproj
Susi/Controllers/SkillListingViewController/SkillListingVCMethods.swift
Susi/Controllers/SkillListingViewController/SkillListingViewController.swift
Susi/Custom Views/Skill Listing Cells/SkillCell.swift
Susi/Custom Views/Skill Listing Cells/SkillListingCollectionView.swift
Susi/Custom Views/Skill Listing Cells/SkillListingTableCell.swift
Susi/Model/Skill.swift
Susi/Shimmer/FBShimmering/FBShimmering.h
Susi/Shimmer/FBShimmering/FBShimmeringLayer.h
Susi/Shimmer/FBShimmering/FBShimmeringLayer.m
Susi/Shimmer/FBShimmering/FBShimmeringView.h
Susi/Shimmer/FBShimmering/FBShimmeringView.m
Susi/Shimmer/LICENSE
Susi/Shimmer/README.md
Susi/Snowboy Files/Susi-Bridging-Header.h
Susi/Storyboards/Main.storyboard

Added Shimmering Effect on SkillListing #485

Added shimmer effect on Skill listing Page

---

Susi/Controllers/PlayerViewController/PlayerViewController.swift
Susi/Youtube-Player/VideoPlayerView.swift

Actual Behaviour :  we close the video player first by tapping 'X'  button on video player and then by tapping blackView .
**Expected Behaviour** : It should Directly close when user Tapped 'X' button on video player . 
Changes: I managed to close video player Directly by 'X' by posting some notification .
we can see issue here #382

Implemented Dismiss youtube video 

---

Susi/Custom Views/Message Cells/ImageCell.swift

Fixes #555 
This problem is occurring when we try to scroll up or down the chat view.  
Changes: Hide the thumbs-up and thumbs-down Icon after successful feedback

Fix: Image Cell Thumbs Up and Down Overlap Issue
